apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: appstudio-qe

configMapGenerator:
- name: quality-dashboard-configmap
  behavior: replace
  envs:
  - configmap.txt

secretGenerator:
  - name: quality-dashboard-auth
    files:
      - users.htpasswd