apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"quality-frontend-route"}}'
