apiVersion: v1
kind: Secret
metadata:
  name: quality-dashboard-secrets
  namespace: appstudio-qe
type: Opaque
data:
  storage-database: "cXVhbGl0eQ=="
  storage-user: "REPLACE_STORAGE_USER"
  storage-password: "REPLACE_STORAGE_PASSWORD"
  github-token: "REPLACE_GITHUB_TOKEN"
  rds-endpoint: "REPLACE_WITH_RDS_ENDPOINT"
  jira-token: "REPLACE_JIRA_TOKEN"
